### ISSUE TITLE
Test::Exception dependency not declared

### ISSUE THREAD

**Issue by andk** [latk/p5-Async-Trampoline#3]
As per subject. Grep:

http://search.cpan.org/grep?release=Async-Trampoline-0.001000;string=Test::Exception;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/87151457

HTH&&Thanks,

**Comment by latk** [comment]
Thank you for your help. Fixed in 0a4bf7c, which was released to CPAN as version 0.001001.
